
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Peppão
 */
public class Chapters extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form Chapters
     */
    
    //create objects
    Images images = new Images();
    TxtEdit txtEdit = new TxtEdit();
    Game game = new Game();
    Thread t1 = new Thread(this);
    Player player = new Player(5, 1, 0, 1);
    Words words = new Words();
    Fase1 fase1 = new Fase1(images.chapter1Icon,images.fase1Background,true, 
                            words.animals,words.food,words.colors);
    Fase2 fase2 = new Fase2(images.chapter2Icon,images.fase2Background,false, 
                            words.city,words.humanParts,words.objects);
    

    public Chapters() {
        initComponents();

        chapter1Image.setIcon(images.chapter1Icon);
        chapter2Image.setIcon(images.chapter2IconBlock);
        chapter3Image.setIcon(images.chapter3IconBlock);
        chapter4Image.setIcon(images.chapter4IconBlock);
        themeChapter1.setIcon(images.chapter1icons);
        themeChapter2.setIcon(images.chapter2icons);
        coin_sprite.setIcon(images.ajustaIcone(images.coin,coin_sprite));
        fire_sprite.setIcon(images.ajustaIcone(images.fire,fire_sprite));
        heart_sprite.setIcon(images.ajustaIcone(images.heart,heart_sprite));
        t1.start();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chapter1Image = new javax.swing.JLabel();
        chapter2Image = new javax.swing.JLabel();
        chapter3Image = new javax.swing.JLabel();
        chapter4Image = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        themeChapter1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        themeChapter2 = new javax.swing.JLabel();
        themeChapter3 = new javax.swing.JLabel();
        themeChapter4 = new javax.swing.JLabel();
        selectUserImage = new javax.swing.JButton();
        borda = new javax.swing.JLabel();
        user_image = new javax.swing.JLabel();
        fire_sprite = new javax.swing.JLabel();
        coin_sprite = new javax.swing.JLabel();
        heart_sprite = new javax.swing.JLabel();
        heart_numbers = new javax.swing.JLabel();
        fire_numbers = new javax.swing.JLabel();
        coin_number = new javax.swing.JLabel();
        desbloqueiaFase2 = new javax.swing.JButton();
        desbloqueiaFase3 = new javax.swing.JButton();
        desbloqueiaFase4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fase1Enter = new javax.swing.JButton();
        fase2Enter = new javax.swing.JButton();
        fase3Enter = new javax.swing.JButton();
        fase4Enter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        chapter1Image.setMaximumSize(new java.awt.Dimension(128, 114));
        chapter1Image.setMinimumSize(new java.awt.Dimension(128, 114));
        chapter1Image.setPreferredSize(new java.awt.Dimension(128, 114));
        getContentPane().add(chapter1Image);
        chapter1Image.setBounds(60, 186, 128, 128);

        chapter2Image.setMaximumSize(new java.awt.Dimension(128, 114));
        chapter2Image.setMinimumSize(new java.awt.Dimension(128, 114));
        chapter2Image.setPreferredSize(new java.awt.Dimension(128, 114));
        getContentPane().add(chapter2Image);
        chapter2Image.setBounds(230, 186, 128, 128);

        chapter3Image.setMaximumSize(new java.awt.Dimension(128, 114));
        chapter3Image.setMinimumSize(new java.awt.Dimension(128, 114));
        chapter3Image.setPreferredSize(new java.awt.Dimension(128, 114));
        getContentPane().add(chapter3Image);
        chapter3Image.setBounds(400, 186, 128, 128);

        chapter4Image.setMaximumSize(new java.awt.Dimension(128, 114));
        chapter4Image.setMinimumSize(new java.awt.Dimension(128, 114));
        chapter4Image.setPreferredSize(new java.awt.Dimension(128, 114));
        getContentPane().add(chapter4Image);
        chapter4Image.setBounds(570, 186, 128, 128);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("CHAPTER 1");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(69, 327, 110, 30);
        getContentPane().add(themeChapter1);
        themeChapter1.setBounds(48, 370, 151, 50);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("CHAPTER 2");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(239, 327, 110, 30);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("CHAPTER 3");
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(409, 327, 110, 30);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("CHAPTER 4");
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(579, 327, 110, 30);
        getContentPane().add(themeChapter2);
        themeChapter2.setBounds(218, 370, 151, 50);
        getContentPane().add(themeChapter3);
        themeChapter3.setBounds(388, 370, 151, 50);
        getContentPane().add(themeChapter4);
        themeChapter4.setBounds(558, 370, 151, 50);

        selectUserImage.setFont(new java.awt.Font("Tahoma", 0, 5)); // NOI18N
        selectUserImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selectUserImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selectUserImageMouseExited(evt);
            }
        });
        selectUserImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectUserImageActionPerformed(evt);
            }
        });
        getContentPane().add(selectUserImage);
        selectUserImage.setBounds(130, 40, 80, 80);
        selectUserImage.setOpaque(false);
        selectUserImage.setContentAreaFilled(false);
        selectUserImage.setBorderPainted(false);
        selectUserImage.setIcon(null);

        borda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        borda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SPRITES/Player/Borda.png"))); // NOI18N
        borda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(borda);
        borda.setBounds(130, 40, 80, 80);

        user_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_image.setText("IMAGE");
        getContentPane().add(user_image);
        user_image.setBounds(130, 40, 80, 80);
        getContentPane().add(fire_sprite);
        fire_sprite.setBounds(390, 60, 38, 40);
        getContentPane().add(coin_sprite);
        coin_sprite.setBounds(250, 60, 38, 42);
        getContentPane().add(heart_sprite);
        heart_sprite.setBounds(508, 60, 49, 40);

        heart_numbers.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        heart_numbers.setForeground(new java.awt.Color(255, 51, 51));
        heart_numbers.setText("0");
        getContentPane().add(heart_numbers);
        heart_numbers.setBounds(577, 57, 29, 40);

        fire_numbers.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        fire_numbers.setForeground(new java.awt.Color(255, 102, 0));
        fire_numbers.setText("0");
        getContentPane().add(fire_numbers);
        fire_numbers.setBounds(448, 57, 29, 40);

        coin_number.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        coin_number.setForeground(new java.awt.Color(255, 255, 0));
        coin_number.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coin_number.setText("999");
        getContentPane().add(coin_number);
        coin_number.setBounds(290, 60, 100, 40);

        desbloqueiaFase2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SPRITES/Chapter/buyFase2.png"))); // NOI18N
        desbloqueiaFase2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desbloqueiaFase2ActionPerformed(evt);
            }
        });
        getContentPane().add(desbloqueiaFase2);
        desbloqueiaFase2.setBounds(252, 140, 80, 40);

        desbloqueiaFase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SPRITES/Chapter/buyFase3.png"))); // NOI18N
        desbloqueiaFase3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desbloqueiaFase3ActionPerformed(evt);
            }
        });
        getContentPane().add(desbloqueiaFase3);
        desbloqueiaFase3.setBounds(422, 140, 80, 40);

        desbloqueiaFase4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SPRITES/Chapter/buyFase4.png"))); // NOI18N
        desbloqueiaFase4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desbloqueiaFase4ActionPerformed(evt);
            }
        });
        getContentPane().add(desbloqueiaFase4);
        desbloqueiaFase4.setBounds(592, 140, 80, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SPRITES/Chapter/wallpaper2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -20, 810, 470);

        fase1Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fase1EnterActionPerformed(evt);
            }
        });
        getContentPane().add(fase1Enter);
        fase1Enter.setBounds(60, 194, 128, 100);

        fase2Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fase2EnterActionPerformed(evt);
            }
        });
        getContentPane().add(fase2Enter);
        fase2Enter.setBounds(230, 194, 128, 100);

        fase3Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fase3EnterActionPerformed(evt);
            }
        });
        getContentPane().add(fase3Enter);
        fase3Enter.setBounds(400, 194, 128, 100);

        fase4Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fase4EnterActionPerformed(evt);
            }
        });
        getContentPane().add(fase4Enter);
        fase4Enter.setBounds(570, 194, 128, 100);

        setSize(new java.awt.Dimension(784, 481));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void startGame(int fase){
        game.setPlayer(this.player);
        game.setFase(fase);
        game.fase1 = this.fase1;
        game.fase2 = this.fase2;
        game.alteraConfig();
        game.ajustaGame();
        game.chapters = this;
        this.setVisible(false);
        game.setVisible(true);
        
    }
    private void selectUserImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectUserImageActionPerformed

        //Choose Image
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Your photo");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        //Filter
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image", "jpg", "png", "jfif");
        fileChooser.setFileFilter(filter);

        int return0 = fileChooser.showOpenDialog(this);

        //set Profile Icon
        if (return0 == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            File txt = new File("imageAdress.txt");
            if (!txt.exists()) {
                try {
                    txt.createNewFile();
                    txtEdit.writeInTxt(txt, file.getPath());
                } catch (IOException ex) {
                    Logger.getLogger(Chapters.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                txtEdit.writeInTxt(txt, file.getPath());

            }
            ImageIcon icon = new ImageIcon(txtEdit.readTxt(txt));
            user_image.setText(null);
            user_image.setIcon(images.ajustaIcone(icon, user_image));

        } else {

        }


    }//GEN-LAST:event_selectUserImageActionPerformed

    private void fase1EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fase1EnterActionPerformed
        // TODO add your handling code here:
        if(fase1.isOpen())startGame(1);

    }//GEN-LAST:event_fase1EnterActionPerformed

    private void selectUserImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectUserImageMouseEntered
        // TODO add your handling code here:
        selectUserImage.setOpaque(true);
        selectUserImage.setContentAreaFilled(true);
        selectUserImage.setBorderPainted(true);
        selectUserImage.setIcon(images.buttonIcone);
    }//GEN-LAST:event_selectUserImageMouseEntered

    private void selectUserImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectUserImageMouseExited
        // TODO add your handling code here:
        selectUserImage.setOpaque(false);
        selectUserImage.setContentAreaFilled(false);
        selectUserImage.setBorderPainted(false);
        selectUserImage.setIcon(null);
    }//GEN-LAST:event_selectUserImageMouseExited

    private void fase2EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fase2EnterActionPerformed
        // TODO add your handling code here:
        if(fase2.isOpen() && game.getFase()!=2 ){
            game.setTrocouDeFase(true);
            startGame(2);
        }
        
    }//GEN-LAST:event_fase2EnterActionPerformed

    private void fase3EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fase3EnterActionPerformed
        // TODO add your handling code here:
        //if(fase3.isOpen())startGame(3);
    }//GEN-LAST:event_fase3EnterActionPerformed

    private void fase4EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fase4EnterActionPerformed
        // TODO add your handling code here:
        //if(fase4.isOpen())startGame(4);
    }//GEN-LAST:event_fase4EnterActionPerformed

    private void desbloqueiaFase2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desbloqueiaFase2ActionPerformed
        // TODO add your handling code here:
        if(player.getCoin()>=200){
            player.setCoin(player.getCoin()-200);
            fase2.setOpen(true);
            this.chapter2Image.setIcon(images.chapter2Icon);
            this.desbloqueiaFase2.setVisible(false);
        }
    }//GEN-LAST:event_desbloqueiaFase2ActionPerformed

    private void desbloqueiaFase3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desbloqueiaFase3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desbloqueiaFase3ActionPerformed

    private void desbloqueiaFase4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desbloqueiaFase4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desbloqueiaFase4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chapters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chapters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chapters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chapters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chapters().setVisible(true);  
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel borda;
    private javax.swing.JLabel chapter1Image;
    private javax.swing.JLabel chapter2Image;
    private javax.swing.JLabel chapter3Image;
    private javax.swing.JLabel chapter4Image;
    private javax.swing.JLabel coin_number;
    private javax.swing.JLabel coin_sprite;
    private javax.swing.JButton desbloqueiaFase2;
    private javax.swing.JButton desbloqueiaFase3;
    private javax.swing.JButton desbloqueiaFase4;
    private javax.swing.JButton fase1Enter;
    private javax.swing.JButton fase2Enter;
    private javax.swing.JButton fase3Enter;
    private javax.swing.JButton fase4Enter;
    private javax.swing.JLabel fire_numbers;
    private javax.swing.JLabel fire_sprite;
    private javax.swing.JLabel heart_numbers;
    private javax.swing.JLabel heart_sprite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton selectUserImage;
    private javax.swing.JLabel themeChapter1;
    private javax.swing.JLabel themeChapter2;
    private javax.swing.JLabel themeChapter3;
    private javax.swing.JLabel themeChapter4;
    private javax.swing.JLabel user_image;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(true){
            this.fire_numbers.setText(""+this.player.getFire());
            this.coin_number.setText(""+this.player.getCoin());
            this.heart_numbers.setText(""+this.player.getVida());
        }
        
    }

    
    

}
